// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSFBj5i7SR6slveYFyHxexwB6KbYcVkUw',
    appId: '1:992900993650:web:5690c4b6b9e5a8602fe8eb',
    messagingSenderId: '992900993650',
    projectId: 'zenfit-e4c1f',
    authDomain: 'zenfit-e4c1f.firebaseapp.com',
    storageBucket: 'zenfit-e4c1f.appspot.com',
    measurementId: 'G-ZVDTCPLQW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPOWVySQNnsUyA-8vRnX0HZp1d0wVla_k',
    appId: '1:992900993650:android:1168ddc9a49da27e2fe8eb',
    messagingSenderId: '992900993650',
    projectId: 'zenfit-e4c1f',
    storageBucket: 'zenfit-e4c1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0E6P8u63h_7QcHt72i_aadN2kB2Av48g',
    appId: '1:992900993650:ios:7817ac9562b240fd2fe8eb',
    messagingSenderId: '992900993650',
    projectId: 'zenfit-e4c1f',
    storageBucket: 'zenfit-e4c1f.appspot.com',
    iosBundleId: 'com.example.zenfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0E6P8u63h_7QcHt72i_aadN2kB2Av48g',
    appId: '1:992900993650:ios:fa62a5006f43bbce2fe8eb',
    messagingSenderId: '992900993650',
    projectId: 'zenfit-e4c1f',
    storageBucket: 'zenfit-e4c1f.appspot.com',
    iosBundleId: 'com.example.zenfit.RunnerTests',
  );
}
